//script.js
//gallery & fullscreen script
function showGallery(category) {
    const backbtn = document.getElementById('back-compagnies');
    const gallery = document.getElementById('gallery');
    const photoGrid = document.getElementById('photo-grid');
    const url = window.location.href;

    if (url == "https://alphazuluspotting.pages.dev/") {
        const footer = document.getElementById('footer')
        const hero = document.getElementById('hero');
        const categories = document.getElementById('categories');
        hero.style.display = 'none';
        footer.style.display = 'none';
        categories.style.display = 'none';
    }

    photoGrid.innerHTML = '';
    backbtn.style.display = 'inline-block';

    const photos = {
        'civil-commercial-airalgerie': [
            {src: '../../photos/civil/airlines/air_algerie/air_algerie (1).jpeg', desc: 'Air Algérie Boeing 737'},
            {src: '../../photos/civil/airlines/air_algerie/air_algerie (2).jpeg', desc: 'Air Algérie Boeing 737'},
            {src: '../../photos/civil/airlines/air_algerie/air_algerie (3).jpeg', desc: 'Air Algérie Airbus A330'},
            {src: '../../photos/civil/airlines/air_algerie/air_algerie (4).jpeg', desc: 'Air Algérie Airbus A330'},
            {src: '../../photos/civil/airlines/air_algerie/air_algerie (5).jpeg', desc: 'Air Algérie Airbus A330'},
            {src: '../../photos/civil/airlines/air_algerie/air_algerie (6).jpeg', desc: 'Air Algérie Airbus A330'},
            {src: '../../photos/civil/airlines/air_algerie/air_algerie (7).jpeg', desc: 'Air Algérie Airbus A330'}
        ],
        'civil-commercial-aircaraibes': [
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (1).jpeg', desc: 'Air Caraïbes Airbus A350'},
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (2).jpeg', desc: 'Air Caraïbes Airbus A350'},
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (3).jpeg', desc: 'Air Caraïbes Airbus A350'},
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (4).jpeg', desc: 'Air Caraïbes Airbus A350'},
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (5).jpeg', desc: 'Air Caraïbes Airbus A350'},
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (6).jpeg', desc: 'Air Caraïbes Airbus A350'},
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (7).jpeg', desc: 'Air Caraïbes Airbus A350'},
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (8).jpeg', desc: 'Air Caraïbes Airbus A330'},
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (9).jpeg', desc: 'Air Caraïbes Airbus A330'},
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (10).jpeg', desc: 'Air Caraïbes Airbus A350'},
            {src: '../../photos/civil/airlines/air_caraibes/air_caraibes (11).jpeg', desc: 'Air Caraïbes Airbus A350'}
        ],
        'civil-commercial-aircorsica': [
            {src: '../../photos/civil/airlines/air_corsica/air_corsica (1).jpeg', desc: 'Air Corsica Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/air_corsica/air_corsica (2).jpeg', desc: 'Air Corsica Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/air_corsica/air_corsica (3).jpeg', desc: 'Air Corsica Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/air_corsica/air_corsica (4).jpeg', desc: 'Air Corsica Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/air_corsica/air_corsica (5).jpeg', desc: 'Air Corsica Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/air_corsica/air_corsica (6).jpeg', desc: 'Air Corsica Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/air_corsica/air_corsica (7).jpeg', desc: 'Air Corsica Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/air_corsica/air_corsica (8).jpeg', desc: 'Air Corsica Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/air_corsica/air_corsica (9).jpeg', desc: 'Air Corsica Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/air_corsica/air_corsica (10).jpeg', desc: 'Air Corsica Airbus A320 Neo'}
        ],
        'civil-commercial-aireuropa': [
            {src: '../../photos/civil/airlines/air_europa/air_europa (1).jpeg', desc: 'Air Europa Boeing 737'},
            {src: '../../photos/civil/airlines/air_europa/air_europa (2).jpeg', desc: 'Air Europa Boeing 737'},
            {src: '../../photos/civil/airlines/air_europa/air_europa (3).jpeg', desc: 'Air Europa Boeing 737'}
        ],
        'civil-commercial-airfrance': [
            {src: '../../photos/civil/airlines/air_france/air_france (1).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (2).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (3).jpeg', desc: 'Air France Boeing 777'},
            {src: '../../photos/civil/airlines/air_france/air_france (4).jpeg', desc: 'Air France Airbus A350'},
            {src: '../../photos/civil/airlines/air_france/air_france (5).jpeg', desc: 'Air France Boeing 777'},
            {src: '../../photos/civil/airlines/air_france/air_france (6).jpeg', desc: 'Air France Airbus A319'},
            {src: '../../photos/civil/airlines/air_france/air_france (7).jpeg', desc: 'Air France Airbus A319'},
            {src: '../../photos/civil/airlines/air_france/air_france (8).jpeg', desc: 'Air France Airbus A319'},
            {src: '../../photos/civil/airlines/air_france/air_france (9).jpeg', desc: 'Air France Airbus A319'},
            {src: '../../photos/civil/airlines/air_france/air_france (10).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (11).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (12).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (13).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (14).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (15).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (16).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (17).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (18).jpeg', desc: 'Air France Airbus A318'},
            {src: '../../photos/civil/airlines/air_france/air_france (19).jpeg', desc: 'Air France Airbus A318'},
            {src: '../../photos/civil/airlines/air_france/air_france (20).jpeg', desc: 'Air France Airbus A318'},
            {src: '../../photos/civil/airlines/air_france/air_france (21).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (22).jpeg', desc: 'Air France Airbus A320'},
            {src: '../../photos/civil/airlines/air_france/air_france (23).jpeg', desc: 'Air France Airbus A318'},
            {src: '../../photos/civil/airlines/air_france/air_france (24).jpeg', desc: 'Air France Airbus A318'},
            {src: '../../photos/civil/airlines/air_france/air_france (25).jpeg', desc: 'Air France Airbus A318'},
            {src: '../../photos/civil/airlines/air_france/air_france (26).jpeg', desc: 'Air France Airbus A318'}
        ],
        'civil-commercial-amelia': [
            {src: '../../photos/civil/airlines/amelia/amelia (1).jpeg', desc: 'Amelia Airbus A319'},
            {src: '../../photos/civil/airlines/amelia/amelia (2).jpeg', desc: 'Amelia Airbus A319'},
            {src: '../../photos/civil/airlines/amelia/amelia (3).jpeg', desc: 'Amelia Airbus A319'},
            {src: '../../photos/civil/airlines/amelia/amelia (4).jpeg', desc: 'Amelia Airbus A319'}
        ],
        'civil-commercial-corsair': [
            {src: '../../photos/civil/airlines/corsair/corsair (1).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (2).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (3).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (4).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (5).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (6).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (7).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (8).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (9).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (10).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (11).jpeg', desc: 'Corsair Airbus A330'},
            {src: '../../photos/civil/airlines/corsair/corsair (12).jpeg', desc: 'Corsair Airbus A330'}
        ],
        'civil-commercial-easyjet': [
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (1).jpeg', desc: 'EasyJet Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (2).jpeg', desc: 'EasyJet Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (3).jpeg', desc: 'EasyJet Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (4).jpeg', desc: 'EasyJet Airbus A319'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (5).jpeg', desc: 'EasyJet Airbus A319'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (6).jpeg', desc: 'EasyJet Airbus A319'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (7).jpeg', desc: 'EasyJet Airbus A319'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (8).jpeg', desc: 'EasyJet Airbus A319'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (9).jpeg', desc: 'EasyJet Airbus A319'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (10).jpeg', desc: 'EasyJet Airbus A319'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (11).jpeg', desc: 'EasyJet Airbus A319'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (12).jpeg', desc: 'EasyJet Airbus A319'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (13).jpeg', desc: 'EasyJet Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (14).jpeg', desc: 'EasyJet Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (15).jpeg', desc: 'EasyJet Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/easy_jet/easy_jet (16).jpeg', desc: 'EasyJet Airbus A320'}
        ],
        'civil-commercial-emirates': [
            {src: '../../photos/civil/airlines/emirates/emirates (1).jpeg', desc: 'Emirates Airbus A380'},
            {src: '../../photos/civil/airlines/emirates/emirates (2).jpeg', desc: 'Emirates Airbus A380'},
            {src: '../../photos/civil/airlines/emirates/emirates (3).jpeg', desc: 'Emirates Airbus A380'},
            {src: '../../photos/civil/airlines/emirates/emirates.jpeg', desc: 'Emirates Boeing 777'},
            {src: '../../photos/civil/airlines/emirates/emirates (4).jpeg', desc: 'Emirates Boeing 777'},
            {src: '../../photos/civil/airlines/emirates/emirates (5).jpeg', desc: 'Emirates Boeing 777'},
            {src: '../../photos/civil/airlines/emirates/emirates (6).jpeg', desc: 'Emirates Boeing 777'},
            {src: '../../photos/civil/airlines/emirates/emirates (7).jpeg', desc: 'Emirates Boeing 777'},
            {src: '../../photos/civil/airlines/emirates/emirates (8).jpeg', desc: 'Emirates Boeing 777'},
            {src: '../../photos/civil/airlines/emirates/emirates (9).jpeg', desc: 'Emirates Boeing 777'},
            {src: '../../photos/civil/airlines/emirates/emirates (10).jpeg', desc: 'Emirates Boeing 777'},
            {src: '../../photos/civil/airlines/emirates/emirates (11).jpeg', desc: 'Emirates Boeing 777'}
        ],
        'civil-commercial-frenchbee': [
            {src: '../../photos/civil/airlines/french_bee/french_bee (1).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (2).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (3).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (4).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (5).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (6).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (7).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (8).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (9).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (10).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (11).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (12).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (13).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (14).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (15).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (16).jpeg', desc: 'French Bee Airbus A350'},
            {src: '../../photos/civil/airlines/french_bee/french_bee (17).jpeg', desc: 'French Bee Airbus A350'}
        ],
        'civil-commercial-iberia': [
            {src: '../../photos/civil/airlines/iberia/iberia (1).jpeg', desc: 'Iberia Airbus A320'},
            {src: '../../photos/civil/airlines/iberia/iberia (2).jpeg', desc: 'Iberia Airbus A320'},
            {src: '../../photos/civil/airlines/iberia/iberia (3).jpeg', desc: 'Iberia Airbus A320'}
        ],
        'civil-commercial-ita': [
            {src: '../../photos/civil/airlines/ita/ita (1).jpeg', desc: 'ITA Airbus A220'},
            {src: '../../photos/civil/airlines/ita/ita (2).jpeg', desc: 'ITA Airbus A220'},
            {src: '../../photos/civil/airlines/ita/ita (3).jpeg', desc: 'ITA Airbus A220'},
            {src: '../../photos/civil/airlines/ita/ita (4).jpeg', desc: 'ITA Airbus A350'}
        ],
        'civil-commercial-luxair': [
            {src: '../../photos/civil/airlines/luxair/luxair (1).jpeg', desc: 'Luxair ATR 72'},
            {src: '../../photos/civil/airlines/luxair/luxair (2).jpeg', desc: 'Luxair ATR 72'},
            {src: '../../photos/civil/airlines/luxair/luxair (3).jpeg', desc: 'Luxair ATR 72'},
            {src: '../../photos/civil/airlines/luxair/luxair (4).jpeg', desc: 'Luxair ATR 72'},
            {src: '../../photos/civil/airlines/luxair/luxair (5).jpeg', desc: 'Luxair ATR 72'},
            {src: '../../photos/civil/airlines/luxair/luxair (6).jpeg', desc: 'Luxair ATR 72'},
            {src: '../../photos/civil/airlines/luxair/luxair (7).jpeg', desc: 'Luxair ATR 72'},
            {src: '../../photos/civil/airlines/luxair/luxair (8).jpeg', desc: 'Luxair ATR 72'}
        ],
        'civil-commercial-pegasus': [
            {src: '../../photos/civil/airlines/pegasus/pegasus (1).jpeg', desc: 'Pegasus Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/pegasus/pegasus (2).jpeg', desc: 'Pegasus Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/pegasus/pegasus (3).jpeg', desc: 'Pegasus Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/pegasus/pegasus (4).jpeg', desc: 'Pegasus Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/pegasus/pegasus (5).jpeg', desc: 'Pegasus Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/pegasus/pegasus (6).jpeg', desc: 'Pegasus Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/pegasus/pegasus (7).jpeg', desc: 'Pegasus Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/pegasus/pegasus (8).jpeg', desc: 'Pegasus Airbus A320 Neo'}
        ],
        'civil-commercial-royalairmaroc': [
            {src: '../../photos/civil/airlines/royal_air_maroc/royal_air_maroc (1).jpeg', desc: 'Royal Air Maroc Boeing 787'},
            {src: '../../photos/civil/airlines/royal_air_maroc/royal_air_maroc (2).jpeg', desc: 'Royal Air Maroc Boeing 787'},
            {src: '../../photos/civil/airlines/royal_air_maroc/royal_air_maroc (3).jpeg', desc: 'Royal Air Maroc Boeing 787'},
            {src: '../../photos/civil/airlines/royal_air_maroc/royal_air_maroc (4).jpeg', desc: 'Royal Air Maroc Boeing 787'},
            {src: '../../photos/civil/airlines/royal_air_maroc/royal_air_maroc (5).jpeg', desc: 'Royal Air Maroc Boeing 737'},
            {src: '../../photos/civil/airlines/royal_air_maroc/royal_air_maroc (6).jpeg', desc: 'Royal Air Maroc Boeing 737'},
            {src: '../../photos/civil/airlines/royal_air_maroc/royal_air_maroc (7).jpeg', desc: 'Royal Air Maroc Boeing 737'}
        ],
        'civil-commercial-tap': [
            {src: '../../photos/civil/airlines/tap/tap (1).jpeg', desc: 'TAP Airbus A320'},
            {src: '../../photos/civil/airlines/tap/tap (2).jpeg', desc: 'TAP Airbus A320'},
            {src: '../../photos/civil/airlines/tap/tap (3).jpeg', desc: 'TAP Airbus A320'},
            {src: '../../photos/civil/airlines/tap/tap (4).jpeg', desc: 'TAP Airbus A330'},
            {src: '../../photos/civil/airlines/tap/tap (5).jpeg', desc: 'TAP Airbus A330'},
            {src: '../../photos/civil/airlines/tap/tap (6).jpeg', desc: 'TAP Airbus A330'},
            {src: '../../photos/civil/airlines/tap/tap (7).jpeg', desc: 'TAP Airbus A330'},
            {src: '../../photos/civil/airlines/tap/tap (8).jpeg', desc: 'TAP Airbus A330'}
        ],
        'civil-commercial-transavia': [
            {src: '../../photos/civil/airlines/transavia/transavia (1).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (2).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (3).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (4).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (5).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (6).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (7).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (8).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (9).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (10).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (11).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (12).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (13).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (14).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (15).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (16).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (17).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (18).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (19).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (20).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (21).jpeg', desc: 'Transavia Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/transavia/transavia (22).jpeg', desc: 'Transavia Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/transavia/transavia (23).jpeg', desc: 'Transavia Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/transavia/transavia (24).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (25).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (26).jpeg', desc: 'Transavia Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/transavia/transavia (27).jpeg', desc: 'Transavia Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/transavia/transavia (28).jpeg', desc: 'Transavia Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/transavia/transavia (29).jpeg', desc: 'Transavia Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/transavia/transavia (30).jpeg', desc: 'Transavia Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/transavia/transavia (31).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (32).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (33).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (34).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (35).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (36).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (37).jpeg', desc: 'Transavia Boeing 737'},
            {src: '../../photos/civil/airlines/transavia/transavia (38).jpeg', desc: 'Transavia Boeing 737'}
        ],
        'civil-commercial-tui': [
            {src: '../../photos/civil/airlines/tui/tui (1).jpeg', desc: 'TUI Boeing 737'},
            {src: '../../photos/civil/airlines/tui/tui (2).jpeg', desc: 'TUI Boeing 737'},
            {src: '../../photos/civil/airlines/tui/tui (3).jpeg', desc: 'TUI Boeing 737'},
            {src: '../../photos/civil/airlines/tui/tui (4).jpeg', desc: 'TUI Boeing 737'},
            {src: '../../photos/civil/airlines/tui/tui.jpeg', desc: 'TUI Boeing 737'}
        ],
        'civil-commercial-vueling': [
            {src: '../../photos/civil/airlines/vueling/vueling (1).jpeg', desc: 'Vueling Airbus A320'},
            {src: '../../photos/civil/airlines/vueling/vueling (2).jpeg', desc: 'Vueling Airbus A320'},
            {src: '../../photos/civil/airlines/vueling/vueling (3).jpeg', desc: 'Vueling Airbus A320'},
            {src: '../../photos/civil/airlines/vueling/vueling (4).jpeg', desc: 'Vueling Airbus A320'},
            {src: '../../photos/civil/airlines/vueling/vueling (5).jpeg', desc: 'Vueling Airbus A320'},
            {src: '../../photos/civil/airlines/vueling/vueling (6).jpeg', desc: 'Vueling Airbus A320'},
            {src: '../../photos/civil/airlines/vueling/vueling (7).jpeg', desc: 'Vueling Airbus A320'},
            {src: '../../photos/civil/airlines/vueling/vueling (8).jpeg', desc: 'Vueling Airbus A320'},
            {src: '../../photos/civil/airlines/vueling/vueling.jpeg', desc: 'Vueling Airbus A320'}
        ],
        'civil-commercial-wizz': [
            {src: '../../photos/civil/airlines/wizz/wizz (1).jpeg', desc: 'Wizz Airbus A321'},
            {src: '../../photos/civil/airlines/wizz/wizz (2).jpeg', desc: 'Wizz Airbus A321'},
            {src: '../../photos/civil/airlines/wizz/wizz (3).jpeg', desc: 'Wizz Airbus A321'}
        ],
        'civil-commercial-aerlingus': [
            {src: '../../photos/civil/airlines/aerlingus/aer_lingus (1).jpeg', desc: 'Aer Lingus Airbus A330'},
            {src: '../../photos/civil/airlines/aerlingus/aer_lingus (2).jpeg', desc: 'Aer Lingus Airbus A330'},
            {src: '../../photos/civil/airlines/aerlingus/aer_lingus (3).jpeg', desc: 'Aer Lingus Airbus A330'},
            {src: '../../photos/civil/airlines/aerlingus/aer_lingus (4).jpeg', desc: 'Aer Lingus Airbus A330'},
            {src: '../../photos/civil/airlines/aerlingus/aer_lingus (5).jpeg', desc: 'Aer Lingus Airbus A330'},
            {src: '../../photos/civil/airlines/aerlingus/aer_lingus (6).jpeg', desc: 'Aer Lingus Airbus A330'},
            {src: '../../photos/civil/airlines/aerlingus/aer_lingus (7).jpeg', desc: 'Aer Lingus Airbus A330'}
        ],
        'civil-commercial-aerolineas-argentinas': [
            {src: '../../photos/civil/airlines/aerolineas_argentinas/aerolineas-argentinas (1).jpeg', desc: 'Aerolineas Argentinas Airbus A330'},
            {src: '../../photos/civil/airlines/aerolineas_argentinas/aerolineas-argentinas (2).jpeg', desc: 'Aerolineas Argentinas Airbus A330'},
            {src: '../../photos/civil/airlines/aerolineas_argentinas/aerolineas-argentinas (3).jpeg', desc: 'Aerolineas Argentinas Airbus A330'},
            {src: '../../photos/civil/airlines/aerolineas_argentinas/aerolineas-argentinas (4).jpeg', desc: 'Aerolineas Argentinas Airbus A330'},
            {src: '../../photos/civil/airlines/aerolineas_argentinas/aerolineas-argentinas (5).jpeg', desc: 'Aerolineas Argentinas Airbus A330'},
            {src: '../../photos/civil/airlines/aerolineas_argentinas/aerolineas-argentinas (6).jpeg', desc: 'Aerolineas Argentinas Airbus A330'}
        ],
        'civil-commercial-aeromexico': [
            {src: '../../photos/civil/airlines/aeromexico/aeromexico.jpeg', desc: 'Aeromexico Boeing 737'}
        ],
        'civil-commercial-aircanada': [
            {src: '../../photos/civil/airlines/air_canada/air_canada (1).jpeg', desc: 'Air Canada Boeing 787'},
            {src: '../../photos/civil/airlines/air_canada/air_canada (2).jpeg', desc: 'Air Canada Boeing 787'},
            {src: '../../photos/civil/airlines/air_canada/air_canada (3).jpeg', desc: 'Air Canada Boeing 787'},
            {src: '../../photos/civil/airlines/air_canada/air_canada (4).jpeg', desc: 'Air Canada Boeing 787'},
            {src: '../../photos/civil/airlines/air_canada/air_canada (5).jpeg', desc: 'Air Canada Boeing 737'}
        ],
        'civil-commercial-american-airlines': [
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (1).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (2).jpeg', desc: 'American Airlines A321 Neo'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (3).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (4).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (5).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (6).jpeg', desc: 'American Airlines Embraer E175LR'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (7).jpeg', desc: 'American Airlines Embraer E175LR'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (8).jpeg', desc: 'American Airlines Airbus A321 Neo'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (9).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (10).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (11).jpeg', desc: 'American Airlines Embraer E175LR'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (12).jpeg', desc: 'American Airlines Airbus A321 Neo'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (13).jpeg', desc: 'American Airlines Airbus A321 Neo'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (14).jpeg', desc: 'American Airlines Airbus A321 Neo'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (15).jpeg', desc: 'American Airlines Airbus A321 Neo'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (16).jpeg', desc: 'American Airlines Airbus A319'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (17).jpeg', desc: 'American Airlines Airbus A319'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (18).jpeg', desc: 'American Airlines Airbus A319'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (19).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (20).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (21).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (22).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (23).jpeg', desc: 'American Airlines Airbus A319'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (24).jpeg', desc: 'American Airlines Airbus A319'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (25).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (26).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (27).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (28).jpeg', desc: 'American Airlines Embraer E175LR'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (29).jpeg', desc: 'American Airlines Embraer E175LR'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (30).jpeg', desc: 'American Airlines Boeing 777'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (31).jpeg', desc: 'American Airlines Boeing 777'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (32).jpeg', desc: 'American Airlines Boeing 777'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (33).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (34).jpeg', desc: 'American Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (35).jpeg', desc: 'American Airlines Boeing 777'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (36).jpeg', desc: 'American Airlines Boeing 787'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (37).jpeg', desc: 'American Airlines Boeing 787'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (38).jpeg', desc: 'American Airlines Boeing 787'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (39).jpeg', desc: 'American Airlines Boeing 787'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (40).jpeg', desc: 'American Airlines Boeing 787'},
            {src: '../../photos/civil/airlines/american_airlines/american-airlines (41).jpeg', desc: 'American Airlines Boeing 737'}
        ],
        'civil-commercial-avianca': [
            {src: '../../photos/civil/airlines/avianca/avianca (1).jpeg', desc: 'Avianca Airbus A330'},
            {src: '../../photos/civil/airlines/avianca/avianca (2).jpeg', desc: 'Avianca Boeing 787'},
        ],
        'civil-commercial-bahamasair': [
            {src: '../../photos/civil/airlines/bahamasair/bahamasair.jpeg', desc: 'Bahamasair Boeing 737'}
        ],
        'civil-commercial-cargojet': [
            {src: '../../photos/civil/airlines/cargojet/cargojet (1).jpeg', desc: 'Cargojet Boeing 767'},
            {src: '../../photos/civil/airlines/cargojet/cargojet (2).jpeg', desc: 'Cargojet Boeing 767'},
            {src: '../../photos/civil/airlines/cargojet/cargojet (3).jpeg', desc: 'Cargojet Boeing 767'},
            {src: '../../photos/civil/airlines/cargojet/cargojet (4).jpeg', desc: 'Cargojet Boeing 767'},
            {src: '../../photos/civil/airlines/cargojet/cargojet (5).jpeg', desc: 'Cargojet Boeing 767'}
        ],
        'civil-commercial-cathay-pacific': [
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (1).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (2).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (3).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (4).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (5).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (6).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (7).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (8).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (9).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (10).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (11).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (12).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (13).jpeg', desc: 'Cathay Pacific Boeing 747'},
            {src: '../../photos/civil/airlines/cathay_pacific/cathay-pacific (14).jpeg', desc: 'Cathay Pacific Boeing 747'}
        ],
        'civil-commercial-china-airlines': [
            {src: '../../photos/civil/airlines/china_airlines/china-airlines (1).jpeg', desc: 'China Airlines Boeing 777'},
            {src: '../../photos/civil/airlines/china_airlines/china-airlines (2).jpeg', desc: 'China Airlines Boeing 777'}
        ],
        'civil-commercial-delta-airlines': [
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (1).jpeg', desc: 'Delta Airlines Boeing 757'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (2).jpeg', desc: 'Delta Airlines Boeing 757'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (3).jpeg', desc: 'Delta Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (4).jpeg', desc: 'Delta Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (5).jpeg', desc: 'Delta Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (6).jpeg', desc: 'Delta Airlines Boeing 757'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (7).jpeg', desc: 'Delta Airlines Boeing 757'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (8).jpeg', desc: 'Delta Airlines Boeing 757'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (9).jpeg', desc: 'Delta Airlines Airbus A321'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (10).jpeg', desc: 'Delta Airlines Airbus A321'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (11).jpeg', desc: 'Delta Airlines Airbus A321'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (12).jpeg', desc: 'Delta Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (13).jpeg', desc: 'Delta Airlines Airbus A319'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (14).jpeg', desc: 'Delta Airlines Airbus A319'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (15).jpeg', desc: 'Delta Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (16).jpeg', desc: 'Delta Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (17).jpeg', desc: 'Delta Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (18).jpeg', desc: 'Delta Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (19).jpeg', desc: 'Delta Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (20).jpeg', desc: 'Delta Airlines Boeing 757'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (21).jpeg', desc: 'Delta Airlines Boeing 757'},
            {src: '../../photos/civil/airlines/delta_airlines/delta-airlines (22).jpeg', desc: 'Delta Airlines Boeing 757'}
        ],
        'civil-commercial-easternair-express': [
            {src: '../../photos/civil/airlines/easternair_express/easternair-express (1).jpeg', desc: 'Eastern Air Express Boeing 737'},
            {src: '../../photos/civil/airlines/easternair_express/easternair-express (2).jpeg', desc: 'Eastern Air Express Boeing 737'}
        ],
        'civil-commercial-fedex': [
            {src: '../../photos/civil/airlines/fedex/fedex (1).jpeg', desc: 'FedEx Boeing 767'},
            {src: '../../photos/civil/airlines/fedex/fedex (2).jpeg', desc: 'FedEx Boeing 767'},
            {src: '../../photos/civil/airlines/fedex/fedex (3).jpeg', desc: 'FedEx Boeing 767'},
            {src: '../../photos/civil/airlines/fedex/fedex (4).jpeg', desc: 'FedEx Boeing 767'}
        ],
        'civil-commercial-frontier': [
            {src: '../../photos/civil/airlines/frontier_airlines/frontier-airlines (1).jpeg', desc: 'Frontier Airlines Airbus A320'},
            {src: '../../photos/civil/airlines/frontier_airlines/frontier-airlines (2).jpeg', desc: 'Frontier Airlines Airbus A320'}
        ],
        'civil-commercial-ibc-airways': [
            {src: '../../photos/civil/airlines/ibc_airways/ibc (1).jpeg', desc: 'IBC Airways Saab 340A'},
            {src: '../../photos/civil/airlines/ibc_airways/ibc (2).jpeg', desc: 'IBC Airways Saab 340A'},
            {src: '../../photos/civil/airlines/ibc_airways/ibc (3).jpeg', desc: 'IBC Airways Saab 340A'},
            {src: '../../photos/civil/airlines/ibc_airways/ibc (4).jpeg', desc: 'IBC Airways Saab 340A'},
            {src: '../../photos/civil/airlines/ibc_airways/ibc (5).jpeg', desc: 'IBC Airways Saab 340A'}
        ],
        'civil-commercial-iberojet': [
            {src: '../../photos/civil/airlines/iberojet/iberojet (1).jpeg', desc: 'Iberojet Airbus A330'},
            {src: '../../photos/civil/airlines/iberojet/iberojet (2).jpeg', desc: 'Iberojet Airbus A330'},
            {src: '../../photos/civil/airlines/iberojet/iberojet (3).jpeg', desc: 'Iberojet Airbus A330'},
            {src: '../../photos/civil/airlines/iberojet/iberojet (4).jpeg', desc: 'Iberojet Airbus A330'}
        ],
        'civil-commercial-jetblue': [
            {src: '../../photos/civil/airlines/jetblue/jetblue (1).jpeg', desc: 'JetBlue Airbus A220'},
            {src: '../../photos/civil/airlines/jetblue/jetblue (2).jpeg', desc: 'JetBlue Airbus A220'},
            {src: '../../photos/civil/airlines/jetblue/jetblue (3).jpeg', desc: 'JetBlue Airbus A220'},
            {src: '../../photos/civil/airlines/jetblue/jetblue (4).jpeg', desc: 'JetBlue Airbus A220'},
            {src: '../../photos/civil/airlines/jetblue/jetblue (5).jpeg', desc: 'JetBlue Airbus A220'}
        ],
        'civil-commercial-latam': [
            {src: '../../photos/civil/airlines/latam/latam (1).jpeg', desc: 'LATAM Airbus A320'},
            {src: '../../photos/civil/airlines/latam/latam (2).jpeg', desc: 'LATAM Boeing 767'},
            {src: '../../photos/civil/airlines/latam/latam (3).jpeg', desc: 'LATAM Boeing 767'},
            {src: '../../photos/civil/airlines/latam/latam (4).jpeg', desc: 'LATAM Boeing 767'},
            {src: '../../photos/civil/airlines/latam/latam (5).jpeg', desc: 'LATAM Boeing 767'},
            {src: '../../photos/civil/airlines/latam/latam (6).jpeg', desc: 'LATAM Boeing 767'},
            {src: '../../photos/civil/airlines/latam/latam (7).jpeg', desc: 'LATAM Boeing 787'},
            {src: '../../photos/civil/airlines/latam/latam (8).jpeg', desc: 'LATAM Boeing 787'},
            {src: '../../photos/civil/airlines/latam/latam (9).jpeg', desc: 'LATAM Boeing 767'}
        ],
        'civil-commercial-lufthansa': [
            {src: '../../photos/civil/airlines/lufthansa/lufthansa (1).jpeg', desc: 'Lufthansa Airbus A350'},
            {src: '../../photos/civil/airlines/lufthansa/lufthansa (2).jpeg', desc: 'Lufthansa Airbus A350'},
            {src: '../../photos/civil/airlines/lufthansa/lufthansa (3).jpeg', desc: 'Lufthansa Airbus A350'},
            {src: '../../photos/civil/airlines/lufthansa/lufthansa (4).jpeg', desc: 'Lufthansa Airbus A350'},
            {src: '../../photos/civil/airlines/lufthansa/lufthansa (5).jpeg', desc: 'Lufthansa Airbus A350'},
            {src: '../../photos/civil/airlines/lufthansa/lufthansa (6).jpeg', desc: 'Lufthansa Airbus A380'},
            {src: '../../photos/civil/airlines/lufthansa/lufthansa (7).jpeg', desc: 'Lufthansa Airbus A380'}
        ],
        'civil-commercial-martinair': [
            {src: '../../photos/civil/airlines/martinair_cargo/martinair-cargo.jpeg', desc: 'Martinair Boeing 747'}
        ],
        'civil-commercial-nac': [
            {src: '../../photos/civil/airlines/nac/nac (1).jpeg', desc: 'Nordic Aviation Boeing 767'},
            {src: '../../photos/civil/airlines/nac/nac (2).jpeg', desc: 'Nordic Aviation Boeing 767'},
            {src: '../../photos/civil/airlines/nac/nac (3).jpeg', desc: 'Nordic Aviation Boeing 767'},
            {src: '../../photos/civil/airlines/nac/nac (4).jpeg', desc: 'Nordic Aviation Boeing 767'}
        ],  
        'civil-commercial-play': [
            {src: '../../photos/civil/airlines/play/play (1).jpeg', desc: 'Play Airbus A321 Neo'},
            {src: '../../photos/civil/airlines/play/play (2).jpeg', desc: 'Play Airbus A321 Neo'}
        ],
        'civil-commercial-rouge': [
            {src: '../../photos/civil/airlines/rouge/rouge (1).jpeg', desc: 'Air Canada Rouge Airbus A319'},
            {src: '../../photos/civil/airlines/rouge/rouge (2).jpeg', desc: 'Air Canada Rouge Airbus A319'}
        ],
        'civil-commercial-sas': [
            {src: '../../photos/civil/airlines/scandinavian_airlines/sas (1).jpeg', desc: 'SAS Airbus A330'},
            {src: '../../photos/civil/airlines/scandinavian_airlines/sas (2).jpeg', desc: 'SAS Airbus A330'},
            {src: '../../photos/civil/airlines/scandinavian_airlines/sas (3).jpeg', desc: 'SAS Airbus A330'},
            {src: '../../photos/civil/airlines/scandinavian_airlines/sas (4).jpeg', desc: 'SAS Airbus A330'},
            {src: '../../photos/civil/airlines/scandinavian_airlines/sas (5).jpeg', desc: 'SAS Airbus A330'},
            {src: '../../photos/civil/airlines/scandinavian_airlines/sas (6).jpeg', desc: 'SAS Airbus A330'},
            {src: '../../photos/civil/airlines/scandinavian_airlines/sas (7).jpeg', desc: 'SAS Airbus A330'}
        ],
        'civil-commercial-southwest': [
            {src: '../../photos/civil/airlines/southwest/southwest (1).jpeg', desc: 'Southwest Boeing 737'},
            {src: '../../photos/civil/airlines/southwest/southwest (2).jpeg', desc: 'Southwest Boeing 737'},
            {src: '../../photos/civil/airlines/southwest/southwest (3).jpeg', desc: 'Southwest Boeing 737'},
            {src: '../../photos/civil/airlines/southwest/southwest (4).jpeg', desc: 'Southwest Boeing 737'},
            {src: '../../photos/civil/airlines/southwest/southwest (5).jpeg', desc: 'Southwest Boeing 737'},
            {src: '../../photos/civil/airlines/southwest/southwest (6).jpeg', desc: 'Southwest Boeing 737'},
            {src: '../../photos/civil/airlines/southwest/southwest (7).jpeg', desc: 'Southwest Boeing 737'},
            {src: '../../photos/civil/airlines/southwest/southwest (8).jpeg', desc: 'Southwest Boeing 737'},
            {src: '../../photos/civil/airlines/southwest/southwest (9).jpeg', desc: 'Southwest Boeing 737'}
        ],
        'civil-commercial-spirit': [
            {src: '../../photos/civil/airlines/spirit_airlines/spirit-airlines (1).jpeg', desc: 'Spirit Airlines Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/spirit_airlines/spirit-airlines (2).jpeg', desc: 'Spirit Airlines Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/spirit_airlines/spirit-airlines (3).jpeg', desc: 'Spirit Airlines Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/spirit_airlines/spirit-airlines (4).jpeg', desc: 'Spirit Airlines Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/spirit_airlines/spirit-airlines (5).jpeg', desc: 'Spirit Airlines Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/spirit_airlines/spirit-airlines (6).jpeg', desc: 'Spirit Airlines Airbus A320 Neo'},
            {src: '../../photos/civil/airlines/spirit_airlines/spirit-airlines (7).jpeg', desc: 'Spirit Airlines Airbus A320 Neo'}
        ],
        'civil-commercial-swiss': [
            {src: '../../photos/civil/airlines/swiss/swiss (1).jpeg', desc: 'Swiss Boeing 777'},
            {src: '../../photos/civil/airlines/swiss/swiss (2).jpeg', desc: 'Swiss Boeing 777'},
            {src: '../../photos/civil/airlines/swiss/swiss (3).jpeg', desc: 'Swiss Boeing 777'},
            {src: '../../photos/civil/airlines/swiss/swiss (4).jpeg', desc: 'Swiss Boeing 777'},
            {src: '../../photos/civil/airlines/swiss/swiss (5).jpeg', desc: 'Swiss Boeing 777'},
            {src: '../../photos/civil/airlines/swiss/swiss (6).jpeg', desc: 'Swiss Boeing 777'},
            {src: '../../photos/civil/airlines/swiss/swiss (7).jpeg', desc: 'Swiss Boeing 777'}
        ],
        'civil-commercial-united-airlines': [
            {src: '../../photos/civil/airlines/united_airlines/united-airlines (1).jpeg', desc: 'United Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/united_airlines/united-airlines (2).jpeg', desc: 'United Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/united_airlines/united-airlines (3).jpeg', desc: 'United Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/united_airlines/united-airlines (4).jpeg', desc: 'United Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/united_airlines/united-airlines (5).jpeg', desc: 'United Airlines Boeing 757'},
            {src: '../../photos/civil/airlines/united_airlines/united-airlines (6).jpeg', desc: 'United Airlines Boeing 737'},
            {src: '../../photos/civil/airlines/united_airlines/united-airlines (7).jpeg', desc: 'United Airlines Boeing 757'}
        ],
        'civil-commercial-viva-aerobus': [
            {src: '../../photos/civil/airlines/viva_aerobus/viva-aerobus (1).jpeg', desc: 'Viva Aerobus Airbus A320'},
            {src: '../../photos/civil/airlines/viva_aerobus/viva-aerobus (2).jpeg', desc: 'Viva Aerobus Airbus A320'}
        ],
        'civil-commercial-volaris': [
            {src: '../../photos/civil/airlines/volaris/volaris (1).jpeg', desc: 'Volaris Airbus A321'},
            {src: '../../photos/civil/airlines/volaris/volaris (2).jpeg', desc: 'Volaris Airbus A321'},
            {src: '../../photos/civil/airlines/volaris/volaris (3).jpeg', desc: 'Volaris Airbus A321'}
        ],
        'general-planes': [
            {src: '../../photos/civil/general/general-p (1).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (2).jpeg', desc: 'Beechcraft BE20'},
            {src: '../../photos/civil/general/general-p (3).jpeg', desc: 'Beechcraft BE20'},
            {src: '../../photos/civil/general/general-p (4).jpeg', desc: 'Beechcraft BE20'},
            {src: '../../photos/civil/general/general-p (5).jpeg', desc: 'Beechcraft BE20'},
            {src: '../../photos/civil/general/general-p (6).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (7).jpeg', desc: 'Aquila AT01'},
            {src: '../../photos/civil/general/general-p (8).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (9).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (10).jpeg', desc: 'Diamond DA42 Twin Star'},
            {src: '../../photos/civil/general/general-p (11).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (12).jpeg', desc: 'Pilatus PC-12 NG'},
            {src: '../../photos/civil/general/general-p (13).jpeg', desc: 'Cessna C206 Stationair'},
            {src: '../../photos/civil/general/general-p (14).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (15).jpeg', desc: 'Piper PA-25 Pawnee'},
            {src: '../../photos/civil/general/general-p (16).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (17).jpeg', desc: 'Piper PA-25 Pawnee'},
            {src: '../../photos/civil/general/general-p (18).jpeg', desc: 'Cessna 182S Skylane'},
            {src: '../../photos/civil/general/general-p (19).jpeg', desc: 'Cessna 182S Skylane'},
            {src: '../../photos/civil/general/general-p (20).jpeg', desc: 'Cirrus SR22'},
            {src: '../../photos/civil/general/general-p (21).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (22).jpeg', desc: ''},
            {src: '../../photos/civil/general/general-p (23).jpeg', desc: ''},
            {src: '../../photos/civil/general/general-p (24).jpeg', desc: ''},
            {src: '../../photos/civil/general/general-p (25).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (26).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (27).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (28).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (29).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (30).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (31).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-p (32).jpeg', desc: 'Cessna C172 Skyhawk'},
            {src: '../../photos/civil/general/general-s.jpeg', desc: 'Flying ad'},
            {src: '../../photos/civil/general/general-p (33).jpeg', desc: 'Cessna C310R'}
        ],
        'general-helico': [
            {src: '../../photos/civil/general/general-h (1).jpeg', desc: 'Robinson R22 Beta II'},
            {src: '../../photos/civil/general/general-h (2).jpeg', desc: 'Robinson R22 Beta II'},
            {src: '../../photos/civil/general/general-h (3).jpeg', desc: 'Robinson R44 Raven II'},
            {src: '../../photos/civil/general/general-h (4).jpeg', desc: 'Robinson R44 Raven II'},
            {src: '../../photos/civil/general/general-h (5).jpeg', desc: 'Robinson R44 Raven II'}
        ],
        'private-planes': [
            {src: '../../photos/civil/private/private-p (1).jpeg', desc: 'Dassault Falcon 7X'},
            {src: '../../photos/civil/private/private-p (2).jpeg', desc: 'Gulfstream G650'},
            {src: '../../photos/civil/private/private-p (3).jpeg', desc: 'Dasault Falcon 900'},
            {src: '../../photos/civil/private/private-p (4).jpeg', desc: 'Embraer Legacy 650'},
            {src: '../../photos/civil/private/private-p (5).jpeg', desc: 'Cessna 525B Citation CJ3+'},
            {src: '../../photos/civil/private/private-p (6).jpeg', desc: 'Cessna 560XL Citation XLS'},
            {src: '../../photos/civil/private/private-p (7).jpeg', desc: 'Cessna 510 Citation Mustang'},
            {src: '../../photos/civil/private/private-p (8).jpeg', desc: 'Dasault Falcon 7X'},
            {src: '../../photos/civil/private/private-p (9).jpeg', desc: 'Dasault Falcon 7X'},
            {src: '../../photos/civil/private/private-p (10).jpeg', desc: 'Cessna Citation Latitude 680A'},
            {src: '../../photos/civil/private/private-p (11).jpeg', desc: 'Bombardier Global 6000'},
            {src: '../../photos/civil/private/private-p (12).jpeg', desc: 'Embraer Legacy 650'},
            {src: '../../photos/civil/private/private-p (13).jpeg', desc: 'Gulfstream G650'},
            {src: '../../photos/civil/private/private-p (14).jpeg', desc: 'Pilatus PC-24 Super Versatile Jet'},
            {src: '../../photos/civil/private/private-p (15).jpeg', desc: 'Cessna 510 Citation Mustang'},
            {src: '../../photos/civil/private/private-p (16).jpeg', desc: 'Cessna 525A Citation CJ2+'},
            {src: '../../photos/civil/private/private-p (17).jpeg', desc: 'Cessna 525A Citation CJ2+'},
            {src: '../../photos/civil/private/private-p (18).jpeg', desc: 'Cessna 680A Citation Latitude'},
            {src: '../../photos/civil/private/private-p (19).jpeg', desc: 'Bombardier Global 7500'},
            {src: '../../photos/civil/private/private-p (21).jpeg', desc: 'Dasault Falcon 2000LX'},
            {src: '../../photos/civil/private/private-p (22).jpeg', desc: 'Dasault Falcon 2000EX'},
            {src: '../../photos/civil/private/private-p (23).jpeg', desc: 'Dassault Falcon 2000EX'},
            {src: '../../photos/civil/private/private-p (24).jpeg', desc: 'Dassault Falcon 2000EX'},
            {src: '../../photos/civil/private/private-p (25).jpeg', desc: 'Bombardier Global 5000'},
            {src: '../../photos/civil/private/private-p (26).jpeg', desc: 'Dassault Falcon 7X'},
            {src: '../../photos/civil/private/private-p (27).jpeg', desc: 'Dasault Falcon 7X'},
            {src: '../../photos/civil/private/private-p (28).jpeg', desc: 'Bombardier Global Express'},
            {src: '../../photos/civil/private/private-p (29).jpeg', desc: 'Cessna Citation Latitude 680A'},
            {src: '../../photos/civil/private/private-p (30).jpeg', desc: 'Pilatus PC-24 Super Versatile Jet'},
            {src: '../../photos/civil/private/private-p (31).jpeg', desc: 'Bombardier Challenger 605'},
            {src: '../../photos/civil/private/private-p (32).jpeg', desc: 'Bombardier Challenger 605'},
            {src: '../../photos/civil/private/private-p (33).jpeg', desc: 'Bombardier Challenger 605'},
            {src: '../../photos/civil/private/private-p (34).jpeg', desc: 'Dassault Falcon 2000LX'},
            {src: '../../photos/civil/private/private-p (35).jpeg', desc: 'Embraer Phenom 300'},
            {src: '../../photos/civil/private/private-p (36).jpeg', desc: 'Cessna Citation XLS'},
            {src: '../../photos/civil/private/private-p (37).jpeg', desc: 'Cessna Citation XLS'},
            {src: '../../photos/civil/private/private-p (38).jpeg', desc: 'Pilatus PC-24 Super Versatile Jet'},
            {src: '../../photos/civil/private/private-p (39).jpeg', desc: 'Beech C90GTx King Air'},
            {src: '../../photos/civil/private/private-p (40).jpeg', desc: 'Beech C90GTx King Air'},
            {src: '../../photos/civil/private/private-p (41).jpeg', desc: 'Bombardier Global 6000'},
            {src: '../../photos/civil/private/private-p (42).jpeg', desc: 'Bombardier Global 6000'},
            {src: '../../photos/civil/private/private-p (43).jpeg', desc: 'Bombardier Global 6000'},
            {src: '../../photos/civil/private/private-p (44).jpeg', desc: 'Hawker 750'},
            {src: '../../photos/civil/private/private-p (45).jpeg', desc: 'Pilatus PC-12 NG'},
            {src: '../../photos/civil/private/private-p (46).jpeg', desc: 'Cessna Citation Latitude'},
            {src: '../../photos/civil/private/private-p (47).jpeg', desc: 'Pilatus PC-12 NG'},
            {src: '../../photos/civil/private/private-p (48).jpeg', desc: 'Pilatus PC-12 NG'},
            {src: '../../photos/civil/private/private-p (49).jpeg', desc: 'Pilatus PC-12 NG'},
            {src: '../../photos/civil/private/private-p (50).jpeg', desc: 'Pilatus PC-12 NG'},
            {src: '../../photos/civil/private/private-p (51).jpeg', desc: 'Cessna Citation CJ4'},
            {src: '../../photos/civil/private/private-p (52).jpeg', desc: 'Cessna Citation CJ4'},
            {src: '../../photos/civil/private/private-p (53).jpeg', desc: 'Pilatus PC-24 Super Versatile Jet'},
            {src: '../../photos/civil/private/private-p (54).jpeg', desc: 'Dassault Falcon 20'},
            {src: '../../photos/civil/private/private-p (55).jpeg', desc: 'Dassault Falcon 20'},
            {src: '../../photos/civil/private/private-p (56).jpeg', desc: 'Dassault Falcon 20'},
            {src: '../../photos/civil/private/private-p (57).jpeg', desc: 'Dassault Falcon 20'},
            {src: '../../photos/civil/private/private-p (58).jpeg', desc: 'AirX Charter Boeing 737'},
            {src: '../../photos/civil/private/private-p (59).jpeg', desc: 'AirX Charter Boeing 737'},
            {src: '../../photos/civil/private/private-p (60).jpeg', desc: 'AirX Charter Boeing 737'}
        ],
        'private-helico': [
            {src: '../../photos/civil/private/private-h (1).jpeg', desc: 'Sikorsky S-76 Spirit'},
            {src: '../../photos/civil/private/private-h (2).jpeg', desc: 'Sikorsky S-76 Spirit'},
            {src: '../../photos/civil/private/private-h (3).jpeg', desc: 'Bell 206B JetRanger'},
            {src: '../../photos/civil/private/private-h (4).jpeg', desc: 'Bell 206B JetRanger'},
            {src: '../../photos/civil/private/private-h (5).jpeg', desc: 'Robinson R44 Raven II'},
            {src: '../../photos/civil/private/private-h (6).jpeg', desc: 'Robinson R44 Raven II'},
            {src: '../../photos/civil/private/private-h (7).jpeg', desc: 'Bell 206B JetRanger'},
            {src: '../../photos/civil/private/private-h (8).jpeg', desc: 'Robinson R44 Raven II'},
            {src: '../../photos/civil/private/private-h (9).jpeg', desc: 'Bell 206B JetRanger'}
        ],
        'governmental-services': [
            {src: '../../photos/civil/governmental_services/gov-services (1).jpeg', desc: 'De Havilland DHC-8 Dash 8'},
            {src: '../../photos/civil/governmental_services/gov-services (2).jpeg', desc: 'Beechcraft B200 King Air'},
            {src: '../../photos/civil/governmental_services/gov-services (3).jpeg', desc: 'Beechcraft B200 King Air'},
            {src: '../../photos/civil/governmental_services/gov-services (4).jpeg', desc: 'Beechcraft B200 King Air'},
            {src: '../../photos/civil/governmental_services/gov-services (5).jpeg', desc: 'De Havilland DHC-8 Dash 8'},
            {src: '../../photos/civil/governmental_services/gov-services (6).jpeg', desc: 'De Havilland DHC-8 Dash 8'}
        ],

        'marine-planes': [
            {src: '../../../photos/military/france/french_navy/marine-p.jpeg', desc: 'Embraer EMB-121 Xingu'},
            {src: '../../../photos/military/france/french_navy/marine-p (1).jpeg', desc: 'Dassault Falcon 10'},
            {src: '../../../photos/military/france/french_navy/marine-p (2).jpeg', desc: 'Dasault Falcon 10'},
            {src: '../../../photos/military/france/french_navy/marine-p (3).jpeg', desc: 'Dasault Falcon 10'},
            {src: '../../../photos/military/france/french_navy/marine-p (4).jpeg', desc: 'Breguet Atlantique II'},
        ],
        'marine-helico': [
            {src: '../../../photos/military/france/french_navy/marine-h (1).jpeg', desc: 'Sud Aviation SA365 Dauphin'},
            {src: '../../../photos/military/france/french_navy/marine-h (2).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (3).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (4).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (5).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (6).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (7).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (8).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (9).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (10).jpeg', desc: 'Aérospatiale AS565 Panther'},
            {src: '../../../photos/military/france/french_navy/marine-h (11).jpeg', desc: 'Aérospatiale AS565 Panther'},
            {src: '../../../photos/military/france/french_navy/marine-h (12).jpeg', desc: 'Aérospatiale AS565 Panther'},
            {src: '../../../photos/military/france/french_navy/marine-h (13).jpeg', desc: 'Aérospatiale AS565 Panther'},
            {src: '../../../photos/military/france/french_navy/marine-h (14).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (15).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (16).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (17).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (18).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (19).jpeg', desc: 'Aérospatiale AS565 Panther'},
            {src: '../../../photos/military/france/french_navy/marine-h (20).jpeg', desc: 'Aérospatiale AS565 Panther'},
            {src: '../../../photos/military/france/french_navy/marine-h (21).jpeg', desc: 'Aérospatiale AS565 Panther'},
            {src: '../../../photos/military/france/french_navy/marine-h (22).jpeg', desc: 'Aérospatiale AS565 Panther'},
            {src: '../../../photos/military/france/french_navy/marine-h (23).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (24).jpeg', desc: 'Sud Aviation SA365 Dauphin'},
            {src: '../../../photos/military/france/french_navy/marine-h (25).jpeg', desc: 'Aérospatiale AS565 Panther'},
            {src: '../../../photos/military/france/french_navy/marine-h (27).jpeg', desc: 'Aérospatiale AS565 Panther'},
            {src: '../../../photos/military/france/french_navy/marine-h (28).jpeg', desc: 'NHIndustries NH90 Caiman Marine'},
            {src: '../../../photos/military/france/french_navy/marine-h (29).jpeg', desc: 'NHIndustries NH90 Caiman Marine'},
            {src: '../../../photos/military/france/french_navy/marine-h (30).jpeg', desc: 'NHIndustries NH90 Caiman Marine'},
            {src: '../../../photos/military/france/french_navy/marine-h (31).jpeg', desc: 'NHIndustries NH90 Caiman Marine'},
            {src: '../../../photos/military/france/french_navy/marine-h (32).jpeg', desc: 'NHIndustries NH90 Caiman Marine'},
            {src: '../../../photos/military/france/french_navy/marine-h (33).jpeg', desc: 'NHIndustries NH90 Caiman Marine'},
            {src: '../../../photos/military/france/french_navy/marine-h (34).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (35).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (36).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (37).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (38).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (39).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (40).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (41).jpeg', desc: 'Airbus Helicopters H160 Guépard'},
            {src: '../../../photos/military/france/french_navy/marine-h (42).jpeg', desc: 'Airbus Helicopters H160 Guépard'},        
        ],
        'gendarmerie': [
            {src: '../../../photos/military/france/national_gendarmerie/gendarmerie (1).jpeg', desc: 'Airbus Helicopters H135'},
            {src: '../../../photos/military/france/national_gendarmerie/gendarmerie (2).jpeg', desc: 'Airbus Helicopters H145'},
            {src: '../../../photos/military/france/national_gendarmerie/gendarmerie (3).jpeg', desc: 'Airbus Helicopters H145'},
            {src: '../../../photos/military/france/national_gendarmerie/gendarmerie (4).jpeg', desc: 'Airbus Helicopters H145'}
        ],
        'terre': [
            {src: '../../../photos/military/france/french_army/french_army (1).jpeg', desc: 'Sud Aviation SA330 Puma'},
            {src: '../../../photos/military/france/french_army/french_army (2).jpeg', desc: 'Sud Aviation SA330 Puma'},
            {src: '../../../photos/military/france/french_army/french_army (3).jpeg', desc: 'Sud Aviation SA330 Puma'},
            {src: '../../../photos/military/france/french_army/french_army (4).jpeg', desc: 'Sud Aviation SA330 Puma'},
            {src: '../../../photos/military/france/french_army/french_army (5).jpeg', desc: 'Sud Aviation SA330 Puma'},
            {src: '../../../photos/military/france/french_army/french_army (6).jpeg', desc: 'NHIndustries NH90 Caiman'},
            {src: '../../../photos/military/france/french_army/french_army (7).jpeg', desc: 'Sud Aviation SA330 Puma'}
        ],
        'aae-helico': [
            { src: "../../../photos/military/france/french_air_space_force/aae-h.jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (1).jpeg", desc: 'Aérospatiale AS550 Fennec' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (2).jpeg", desc: 'Aérospatiale AS550 Fennec' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (3).jpeg", desc: 'Aérospatiale AS550 Fennec' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (4).jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (5).jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (6).jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (7).jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (8).jpeg", desc: 'Aérospatiale AS550 Fennec' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (9).jpeg", desc: 'Aérospatiale AS550 Fennec' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (10).jpeg", desc: 'Aérospatiale AS550 Fennec (Special Livery)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (11).jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (12).jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (13).jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (14).jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (15).jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (16).jpeg", desc: 'Aérospatiale AS332 Super Puma' },
            { src: "../../../photos/military/france/french_air_space_force/aae-h (17).jpeg", desc: 'Aérospatiale AS332 Super Puma' }
        ],
        'aae-planes': [
            { src: "../../../photos/military/france/french_air_space_force/aae-p (1).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (2).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (3).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (4).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (5).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (6).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (7).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (8).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (9).jpeg", desc: 'Airbus A400M Atlas' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (10).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (11).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (12).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (13).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (14).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (15).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (16).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (17).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (18).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (19).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (20).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (21).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (22).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (23).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (24).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (25).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (26).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (27).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (28).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (29).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (30).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (31).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (32).jpeg", desc: 'Beechcraft Super King Air 350' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (33).jpeg", desc: 'Beechcraft Super King Air 350' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (34).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (35).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (36).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (37).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (38).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (39).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (40).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (41).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (42).jpeg", desc: 'Dassault Falcon 900 (French presidential jet)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (43).jpeg", desc: 'Dassault Falcon 900 (French presidential jet)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (44).jpeg", desc: 'Pilatus PC-21' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (45).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (46).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (47).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (48).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (49).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (50).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (51).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (52).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (53).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (54).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (55).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (56).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (57).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (58).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (59).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (60).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (61).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (62).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (63).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (64).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (65).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (66).jpeg", desc: 'Smiley drawn by Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (67).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (68).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (69).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (70).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (71).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (72).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (73).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (74).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (75).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (76).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (77).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (78).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (79).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (80).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (81).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (82).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (83).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (84).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (85).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (86).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (87).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (88).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (89).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (90).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (91).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (92).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (93).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (94).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (95).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (96).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (97).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (98).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (99).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (100).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (101).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (102).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (103).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (104).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (105).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (106).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (107).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (108).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (109).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (110).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (111).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (112).jpeg", desc: 'Heart drawn by Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (113).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (114).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (115).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (116).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (117).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (118).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (119).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (120).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (121).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (122).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (123).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (124).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (125).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (126).jpeg", desc: 'Extra Flugzeugbau Extra 330' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (127).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (128).jpeg", desc: 'Embraer EMB-121 Xingu' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (129).jpeg", desc: 'Beechcraft King Air 200' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (130).jpeg", desc: 'Dassault Rafale C' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (131).jpeg", desc: 'CASA CN-235' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (132).jpeg", desc: 'CASA CN-235' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (133).jpeg", desc: 'CASA CN-235' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (134).jpeg", desc: 'CASA CN-235' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (135).jpeg", desc: 'CASA CN-235' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (136).jpeg", desc: 'CASA CN-235' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (137).jpeg", desc: 'Airbus A400M Atlas' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (138).jpeg", desc: 'Airbus A400M Atlas' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (139).jpeg", desc: 'Airbus A400M Atlas' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (140).jpeg", desc: 'Airbus A400M Atlas' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (141).jpeg", desc: 'Airbus A400M Atlas' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (142).jpeg", desc: 'Embraer EMB-121 Xingu' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (143).jpeg", desc: 'Socata TBM-700' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (144).jpeg", desc: 'Dasault Falcon 7X' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (145).jpeg", desc: 'Dasault Falcon 7X' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (146).jpeg", desc: 'Dasault Falcon 7X' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (147).jpeg", desc: 'Dasault Falcon 7X' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (148).jpeg", desc: 'Dasault Falcon 7X' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (149).jpeg", desc: 'Dasault Falcon 7X' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (150).jpeg", desc: 'Dasault Falcon 7X' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (151).jpeg", desc: 'Dasault Falcon 7X' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (152).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (153).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (154).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (155).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (156).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (157).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (158).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (159).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (160).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (161).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (162).jpeg", desc: 'Dassault Breguet / Dornier Alpha Jet (Patrouille de France)' },
            { src: "../../../photos/military/france/french_air_space_force/aae-p (163).jpeg", desc: 'Dassault Rafale C (Rafale Solo Display 2025)' },
        ],
        'historical': [
            {src: './photos/historical/historical (1).jpeg', desc: 'Douglas DC-3 + two North American T-6 Texan'},
            {src: './photos/historical/historical (2).jpeg', desc: 'Douglas DC-3 + two North American T-6 Texan'},
            {src: './photos/historical/historical (3).jpeg', desc: 'Douglas DC-3 + two North American T-6 Texan'},
            {src: './photos/historical/historical (4).jpeg', desc: 'Douglas DC-3 + two North American T-6 Texan'},
            {src: './photos/historical/historical (5).jpeg', desc: 'Douglas DC-3 + two North American T-6 Texan'},
            {src: './photos/historical/historical (6).jpeg', desc: 'Douglas DC-3 + two North American T-6 Texan'},
            {src: './photos/historical/historical (7).jpeg', desc: 'Douglas DC-3 + two North American T-6 Texan'},
            {src: './photos/historical/historical (8).jpeg', desc: 'Douglas DC-3 + two North American T-6 Texan'}
        ],
    };

    window.scrollTo({
        top: 0,
        behavior: 'instant'
    });

    const selectedPhotos = photos[category] || [];
    selectedPhotos.forEach(photo => {
        const div = document.createElement('div');
        div.className = 'photo-item';
        // Remplacer background-image par une balise <img>
        const img = document.createElement('img');
        img.src = photo.src;
        img.alt = photo.desc;
        img.loading = 'lazy'; // Activer le lazy loading
        img.style.width = '100%';
        img.style.height = '100%';
        img.style.objectFit = 'cover'; // Simuler l'effet de background-size: cover
        div.appendChild(img);
        div.onclick = () => showFullscreen(photo.src, photo.desc);
        photoGrid.appendChild(div);
    });

    gallery.style.display = 'block';

    if (url != "https://alphazuluspotting.pages.dev/") {
        document.querySelector('.subcategories').style.display = 'none';
    }
    
}

function showFullscreen(src, desc) {
    const fullscreen = document.getElementById('fullscreen');
    document.getElementById('fullscreen-img').src = src;
    document.getElementById('fullscreen-desc').textContent = desc;
    fullscreen.style.display = 'flex';
    document.body.style.overflow = 'hidden';
}

function closeFullscreen() {
    document.getElementById('fullscreen').style.display = 'none';
    document.body.style.overflow = 'auto';
}